[project]
name = "build-an-agent"
description = "Build An Agent"
version = "0.0.1"
dependencies = [
    "jupyterlab>=4.0.0",
    "jupyterlab-git>=0.44.0",
    "jupyter-app-launcher>=0.1.0",
]

[tool.brev]
instance_type = "l40s-48gb.1x"
cloud = "crusoe"
ports = [ { name = "jupyter", port = 8888 } ]
